---
title: "Prepare HSLS Data for Analysis"
author: "Kristian Edosomwan"
date: "2026-04-17"
output:
  html_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Setup
## Load Libraries

```{r libraries}
library(haven)
library(tidyverse)
library(labelled)
library(psych)
library(broom)
library(mice)
library(mitools)
library(sjPlot)
```

## Load Dataset
```{r}
hsls_raw <- read_dta("hsls_17_student_pets_sr_v1_0.dta")
```

## Subset Dataset Based on Grant Application and LowerCase
```{r}
hsls_subset <- hsls_raw %>% dplyr::select(
# Student Demographics & Background
STU_ID, X1SES, X1SESQ5, X1RACE, X1SEX, X1SES_U, X2SES, X2SES_U, X2RACE, X2SESQ5, X2SEX, X2SESQ5_U, X1PAREDU, X1POVERTY185, X2PAREDU, X2POVERTY185, X1POVERTY130, X1POVERTY, X1FAMINCOME, X2FAMINCOME, X1PAR1RACE, X1PAR2RACE, P1ELLEVER, X1DUALLANG,
# Student Mathematics Scores and STEM GPA
S1M8GRADE, S1S8GRADE, X1TXMQUINT, X1TXMTH, X1TXMTSCOR, X2TXMQUINT, X2TXMTH, X2TXMTSCOR, X3TGPAHIMTH, X3TGPAHISCI, X3TGPAMAT, X3TGPASTEM,
# Student Mathematics Scales [in Red] and Component Items
X1MTHEFF, S1MTESTS, S1MTEXTBOOK, S1MSKILLS, S1MASSEXCL,
X1MTHID, S1MPERSON1, S1MPERSON2,
X1MTHINT, S1MENJOYING, S1MWASTE, S1MBORING, S1FAVSUBJ, S1LEASTSUBJ, S1MENJOYS,
X1MTHUTI, S1MUSELIFE, S1MUSECLG, S1MUSEJOB,
X2MTHEFF, S2MTESTS, S2MTEXTBOOK, S2MSKILLS, S2MASSEXCL,
X2MTHID, S2MPERSON1, S2MPERSON2,
X2MTHINT_R, S2MENJOYING, S2MWASTE, S2MBORING, S2FAVSUBJ, S2MENJOYS,
X2MTHUTI, S2MUSELIFE, S2MUSECLG, S2MUSEJOB,
X2MEFFORT, S2MATTENTION, S2MONTIME, S2MSTOPTRYING, S2MGETBY,
# Student Perceptions of Mathematics Teacher
S1MTCHRESPCT, S1MTCHFAIR, S1MTCHCONF, S1MTCHMISTKE, S1MTCHTREAT, S1MTCHINTRST, S1MTCHMFDIFF, S1MTCHEASY, S2MTCHTREAT, S2MTCHINTRST, S2MTCHEASY, S2MTCHTHINK, S2MTCHGIVEUP,
# Mathematics and Science Secondary Coursework
S1M8, S1S8, X3T1CREDALG1, X3T1CREDALG2, X3T1CREDCALC, X3T1CREDCHEM, X3T1CREDPHYS, X3T1CREDPREC, X3T1CREDSTAT, X3TCREDAPMTH, X3TCREDAPSCI, X3TCREDMAT, X3TCREDMTSC, X3TCREDSTEM, X3THIMATH, X3THIMATH9, X3THISCI, X3THISCI9, X3TWHENALG1, S2HIMATH12, S2HISCIENCE12,
# Postsecondary STEM major and coursework
X4RFDGMJSTEM, X5STEMCRED, X5STEM1ATT, X5STEM1ERN, X5STEM1GPA, X5STEM3ATT, X5STEM3ERN, X5STEM3GPA,
# Parent Expectations & Educational Engagement
P1EDUASPIRE, P1EDUEXPECT, P1FUNDRAISE, P1HONORS, P1MTHHWEFF, P1PTCONFER, P1PTOMTG, P1COUNSELOR, P1SCHEVENT, P1SCHMTG, P1SCIFAIR, P1SCIHWEFF, P1SCIPROJ, P1STEMDISC, P1VOLUNTEER, P1ABLEBA, P2EDUASP, P2EDUEXP, P2ABLEBA, P2DISCCOURSES, P2MTHHWEFF, P2SCIHWEFF, P2SCIPROJ, P2STEMDISC, S1DADTALKM, S1DADTALKS, S1MOMTALKM, S1MOMTALKS,
# Math Teacher Expectations and Beliefs [Scales in Red]
X1TMCOMM, M1SHRIDEAS, M1WORKSHOP, M1SHRSTWRK, M1SHRLESSONS, M1SHRBELIEFS, M1SHRMTHDS, M1SHRELL, M1SHRAPPRCH, M1SHRCONTENT, M1EFFECTIVE, M1MENTOR, M1CHAIR, 
X1MTHEFF, M1FAMILY, M1DISCIPLINE, M1STUACHIEVE, M1PARENT, M1RETAIN, M1REDIRECT, M1GETTHRU, M1HOMEFX, 
X1TMEXP, M1TEACHING, M1LEARNING, M1BELIEVE, M1CLEARGOALS, M1GIVEUP, M1CARE, M1EXPECT, M1WORKHARD, 
X1TMPRINC, M1PRESSURES, M1POORJOBRES, M1PSETSPRIO, M1PSCHVISION, M1PCOMEXP, M1PINNOVATE, M1PCONSULTS, 
X1TMRESP, M1TSCHDISC, M1TIMPROVE, M1TSETSTDS, M1TSELFDEV, M1THELPBEST, M1TALLLEARN, M1TFAIL, 
X1TSCOMM, M1SHRIDEAS, M1WORKSHOP, M1SHRSTWRK, M1SHRLESSONS, M1SHRBELIEFS, M1SHRMTHDS, M1SHRELL, M1SHRAPPRCH, M1SHRCONTENT, M1EFFECTIVE, M1MENTOR, M1CHAIR,
# Math Teacher Instructional Practices/Focus
M1GROUP, M1ASSIGN, M1INTEREST, M1CONCEPTS, M1ALGORITHM, M1COMPSKILLS, M1PROBLEM, M1REASON, M1IDEAS, M1PREPARE, M1LOGIC, M1HISTORY, M1EXPLAIN, M1BUSINESS, M1COMPUTE, M1TEST, M1AUTONOMY, 
# School Characteristics 
X1CONTROL, X2CONTROL, X3CONTROL, X4CONTROL, X1LOCALE, X2LOCALE, X3LOCALE, X4LOCALE, X4PS1CTRL, 
# Sampling Weights
W1STUDENT, W1PARENT, W1MATHTCH, W2STUDENT, starts_with("W2W1STU"), W2PARENT, W2W1PAR, W3STUDENT, W3W1STU, W3W1W2STU, W3W2STU, W3HSTRANS, W3STUDENTTR, W3W1STUTR, W3W1W2STUTR, W3W2STUTR, W4STUDENT, W4W1STU, W4W1STUP1, W4W1STUP1P2, W4W1W2W3STU, W5PSTRANS, W5PSRECORDS, W5W1W2W3W4PSTRANS, W5W1W2W3W4PSRECORDS, W3W1MATHTCH,

# Parent respondent status
X1PARRESP, starts_with("W3HSTRAN")
)

names(hsls_subset) <- tolower(names(hsls_subset))
```

## View Data Subset with Missing Values
```{r}
# replace missing values
hsls_subset[hsls_subset == -9] <- NA # missing
hsls_subset[hsls_subset == -8] <- NA # non-response
hsls_subset[hsls_subset == -7] <- NA # legit skip
hsls_subset[hsls_subset == -6] <- NA # not applicable
hsls_subset[hsls_subset == -4] <- NA # not administered
hsls_subset[hsls_subset == -3] <- NA # carry through missing
hsls_subset[hsls_subset == -1] <- NA # don't know

# drop unused labels
hsls_subset <- labelled::drop_unused_value_labels(hsls_subset)

## view data after replacing missing values
#view_df(hsls_subset, show.frq = TRUE, show.prc = TRUE, show.na = TRUE,  sort = TRUE)

```

# Variable manipulation

## Filter 
```{r}
# drop nonresponses based on having unit non-response for highest math class in 8th grade, which we are using as our first time point, and highest math class in spring 2012, and higest math credit. also those not taking math 9th grade
hsls <- hsls_subset %>% dplyr::filter(!is.na(x3thimath9), !is.na(x1parresp))
```

## Math coursework
```{r}
hsls %>% count(x3thimath9, s1m8)
# ---------------------------
# Treatment variables
# ---------------------------
hsls <- hsls_subset %>%
  mutate(
    math_cred = x3tcredmat,
    math_cred_semester = x3tcredmat*2,
    math_cred3 = ifelse(math_cred >= 3, 1, 0),
    math_cred4 = ifelse(math_cred >=4, 1, 0),
    
    # early algebra
      middle_math = case_when(
        s1m8 < 4 ~ 1,
        s1m8 %in% c(4,5,7) ~ 2,
        s1m8 %in% 6 ~ 3,
      TRUE ~ NA_real_
    ),

    advanced_mathematics = ifelse(x3thimath > 7, 1, 0),
    # adv_math: binary numeric (0 = not advanced, 1 = advanced)
    
    highest_math = case_when(
      x3thimath  %in% c(0,1,2,3,4,5) ~ 1,    # Geometry or Below
      x3thimath  %in% c(6) ~ 2,              # Algebra II
      x3thimath  %in% c(7,8,9,11) ~ 3,       # Advanced Math
      x3thimath  %in% c(10, 12, 13) ~ 4,              # Calculus or AP/IB math
    TRUE ~ NA_real_),
    
    adv_math1 = case_when(
      x3thimath9 <= 4 ~ 0, # algebra 1 and below
      x3thimath9 > 4  ~ 1, # algebra one or more advanced
      TRUE ~ NA_real_
    ),
    
    adv_math2 = case_when(
      s2himath12 <= 5 ~ 0, #geometry and below
      #  analytic geo, trig, precalc, calc, stats, ib/ap
      s2himath12 %in% c(6,7,8,9,10,11,12,16) ~ 1, 
      s2himath12 %in% c(13,14,15,18,19) ~ 0, #integ math, business, other
      TRUE ~ NA_real_
    ),
    
    math_level2 = ordered(
      case_when(
       # geo, alg 1, pre-alg, other, business, integrated math 1/2
      s2himath12 %in% c(1,2,5,13,14,18,19) ~ "remedial",
      # alg 2, integrated math III
      s2himath12 %in% c(3,15) ~ "on-level", 
       # trig/precalc, alg3, analytic geometry
      s2himath12 %in% c(4,6,7,8) ~ "advanced",
      # stats, calc, AP/IB
      s2himath12 %in% c(9,10,11,12,16) ~ "double advanced",
      TRUE ~ NA_character_
    ),
     levels = c("remedial", "on-level", 
                 "advanced", "double advanced")
  ),


    # math_4level: ordinal categorical (low → high)
    math_level1 = ordered(
      case_when(
        x3thimath9 <= 3 ~ "remedial",
        x3thimath9 == 4 ~ "on-level",
        x3thimath9 == 5 ~ "advanced",
        x3thimath9 >= 6 ~ "double advanced",
        TRUE ~ NA_character_
        
      ),
      levels = c("remedial", "on-level", 
                 "advanced", "double advanced")
    )
  )
```

## Demographics & Controls
```{r}
# ---------------------------
# Controls
# ---------------------------
hsls <- hsls %>%
  mutate(
    # urban: binary numeric
    urban = ifelse(x1locale == 1, "1 urban", "0 non-urban"),

    # math_score: continuous numeric
    math_score = ifelse(x1txmquint < 0, NA, x1txmtscor),
    
    # early algebra: binary numeric
    early_algebra = ifelse(s1m8 >=4 & s1m8 !=9, 1, 0),

    # public: binary numeric (1 = public, 0 = private)
    public = case_when(
      x1control == 1 ~ "1 public",
      x1control == 2 ~ "0 private"
    )
  )

# ---------------------------
# Demographics
# ---------------------------
hsls <- hsls %>%
  mutate(
    # first_gen: binary numeric
    first_gen = ifelse(x1paredu <= 3, 1,0),
    par_ba = ifelse(x1paredu >= 4, 1, 0),

    # female: binary numeric (1 = female)
    female = ifelse(x1sex == 2, 1, 0),

    # frpl: binary numeric
    frpl = ifelse(x1poverty185 == 0, "0 no", "1 yes"),
    
    # SES
    ses_quintile1 = x1sesq5,
    ses_quintile2 = x2sesq5,
    ses1 = x1ses,
    ses2 = x2ses,


    # pov_level: ordinal numeric (1 = deepest poverty → 4 = no poverty)
    pov_level = ordered(
      case_when(
        x1poverty185 == 0  ~ 4,
        x1poverty185 == 1 & x1poverty130 == 0 ~ 3,
        x1poverty130 == 1 & x1poverty == 0 ~ 2,
        x1poverty == 1 ~ 1
      ),
      levels = c(1, 2, 3, 4)
    ),

    # first_lang: nominal categorical
    first_lang = factor(
      case_when(
        x1duallang == 1 ~ "English only",
        x1duallang == 2 ~ "Non-English only",
        x1duallang == 3 ~ "English and another equally"
      )
    ),

    # esl_program: binary numeric
    esl_program = case_when(
      p1ellever == 1 ~ "1 yes",
      p1ellever == 2 ~ "0 no"
    ),

    # stud_race: nominal categorical
    stud_race = factor(
      case_when(
        x1race %in% c(1, 7) ~ "Indigenous",
        x1race == 2        ~ "Asian",
        x1race == 3        ~ "Black",
        x1race %in% c(4,5) ~ "Latinx",
        x1race == 6        ~ "Multiple",
        x1race == 8        ~ "White"
      )
    ),

    # par_race: nominal categorical
    par_race = factor(
      case_when(
        x1par1race == 2        ~ "Asian",
        x1par1race == 3        ~ "Black",
        x1par1race %in% c(4,5) ~ "Latinx",
        x1par1race == 6        ~ "Multiple",
        x1par1race == 8        ~ "White",
        x1par1race == 9        ~ "Indigenous"
      )
    )
  )
```

## Math Affect

```{r}
# ---------------------------

# ---------------------------

hsls <- hsls %>%  
 mutate(
    scale_math_id1  = x1mthid,
    scale_math_id2  = x2mthid,
    scale_math_eff1 = x1mtheff,
    scale_math_eff2 = x2mtheff,
    scale_math_uti1 = x1mthuti,
    scale_math_uti2 = x2mthuti,
    scale_math_int1 = x1mthint,
    scale_math_int2 = x2mthint_r
  )

vars_to_numeric <- c("s1mtchmfdiff","s1mtchtreat","s1mtchintrst","s1mtcheasy",
                     "s2mtchtreat","s2mtchintrst","s2mtcheasy")

hsls <- hsls %>%
  mutate(
    math_treat1 = as.numeric(s1mtchtreat),
    math_treat2 = as.numeric(s2mtchtreat),
    
    # reverse code so that more agreement with positive is higher
    math_easy1 =  5 - as.numeric(s1mtcheasy),
    math_easy2 =  5 - as.numeric(s2mtcheasy),
    math_interest1 =  5 - as.numeric(s1mtchintrst),
    math_interest2 =  5 - as.numeric(s2mtchintrst))

# Create Math Teacher Scale

hsls <- hsls %>%
  mutate(
    scale_math_teach1 = 
      rowMeans(
        across(c(math_treat1, math_easy1, math_interest1))),
    scale_math_teach2 = 
      rowMeans(
        across(c(math_treat2, math_easy2, math_interest2))),
    teach_treat_std1 = as.numeric(scale(scale_math_teach1)),
    teach_treat_std2 = as.numeric(scale(scale_math_teach2))
    )
```

## Parent involvement

```{r}
# ---------------------------
# Parent school involvement
# ---------------------------
hsls <- hsls %>%
  mutate(
    # par_sch_inv: count variable (numeric, Poisson-type)
    par_sch_inv = rowSums(select(., p1schevent, p1volunteer, 
                                 p1fundraise, p1ptconfer, p1ptomtg, p1schmtg),
                          na.rm = FALSE)
  )


# ---------------------------
# Parent expectations
# ---------------------------
hsls <- hsls %>%
  mutate(
    able_ba1 = 5 - p1ableba,# reverse code this so that higher numbers are higher ratings of student ability to complete BA
    exp_ba1 = ifelse(p1eduexpect >= 6, 1, 0),
    # par_exp: ordinal numeric (low → high expectations), based on the parent aspirations sections wtih IDK grouped with lowest level
    par_exp1 = case_when(
        p1eduexpect %in% c(1,2, 11)    ~ 1, # IDK, high school/ged
        p1eduexpect %in% c(3,4)      ~ 2, # associate
        p1eduexpect %in% c(5,6)      ~ 3, # BA
        p1eduexpect %in% c(7,8)      ~ 4, # MA
        p1eduexpect %in% c(9,10)     ~ 5), # PhD/Professional
    par_asp1 = case_when(
        p1eduaspire  == 2      ~ 1,
        p1eduaspire  == 4      ~ 2,
        p1eduaspire  == 6      ~ 3,
        p1eduaspire  == 8      ~ 4,
        p1eduaspire  == 10     ~ 5))

# ---------------------------
# Create Scales
# ---------------------------
hsls <- hsls %>%
  mutate(
    # na.rm = TRUE means it will calculate based on available values
    psd = rowMeans(select(., s1momtalkm, s1dadtalkm, s1momtalks, s1dadtalks), na.rm = TRUE),
    psd_scale = scale(psd),
    phbae = rowMeans(select(., p1eduexpect, p1eduaspire, able_ba1), na.rm = TRUE),
    phbae_scale = scale(phbae)
  )

```

# Save Modified Data

```{r}
################################################################################
# Save Subset (WIDE)
################################################################################


write_dta(hsls, "hsls_subset_wide.dta")
```

# Subset, reshape, save
```{r}

df <- hsls %>%
  dplyr::select(
    scale_math_id1, scale_math_id2,
    advanced_mathematics, highest_math,
    adv_math1, adv_math2,
    math_level1, math_level2,
    math_cred3, math_cred4,
    scale_math_eff1, scale_math_eff2,
    scale_math_uti1, scale_math_uti2,
    scale_math_int1, scale_math_int2,
    teach_treat_std1, teach_treat_std2,
    math_treat1, math_easy1, math_interest1, 
    math_treat2, math_easy2, math_interest2,
    ses_quintile1, ses_quintile2,
    ses1, ses2, x1race,
    starts_with("math_teach"),
    early_algebra, math_score, middle_math,
    first_lang, stud_race, par_race, female, 
    math_cred, math_cred_semester,
    phbae_scale, phbae, psd_scale, psd,
    s1dadtalks, s1momtalks, s1dadtalkm, s1momtalkm,
    par_exp1, par_asp1, able_ba1,
    par_sch_inv, 
    urban, public,
    stu_id, starts_with("w2w1s")
  )


df_long <- df %>%
  pivot_longer(
    cols = c(scale_math_id1, scale_math_id2,
             scale_math_eff1, scale_math_eff2,
             scale_math_uti1, scale_math_uti2,
             scale_math_int1, scale_math_int2,
             teach_treat_std1, teach_treat_std2,
             math_treat1, math_easy1, math_interest1, 
             math_treat2, math_easy2, math_interest2,
             adv_math1, adv_math2, math_level1, math_level2,
             ses_quintile1, ses_quintile2, ses1, ses2),
    names_to = c(".value","time"),
    names_pattern = "(.*)([12])"
  ) %>%
  mutate(
    time = if_else(time == "1", 0, 1)
  )

write_dta(df_long, "hsls_subset_long.dta")
```



# Imputation

## check missing
```{r}
df_imp_prep <- df_long %>% as_factor() %>% dplyr::select(
  -par_exp1:s1dadtalks)

colSums(is.na(df_imp_prep))
```

## Dry run
```{r}
meth <- mice::mice(df_imp_prep, maxit = 0, m = 1)
meth$method
```

## Impute!
```{r}
start_time <- Sys.time()

df_imp <- mice(df_imp_prep, m = 20, nnet.MaxNWts = 3000)
end_time <- Sys.time()
end_time - start_time
save(df_imp, file = "data/df_imp.rdata")


```





