---
title: "Math Teacher Focus"
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## Load Libraries and dataset
```{r}

```
## Teacher EFA

### Check Number of Factors
```{r}
# what teachers emphasize in class
mtch_focus <- hsls %>% dplyr::select(m1interest, m1concepts, m1algorithm, m1compskills, m1problem, m1reason, m1ideas, m1prepare, m1logic, m1history, m1explain, m1business, m1compute, m1test)
N_FACTORS(mtch_focus)

# efficacy variables
mtch_efficacy <- hsls %>% dplyr::select(m1family, m1discipline, m1stuachieve, m1parent, m1retain, m1redirect, m1getthru, m1homefx)
N_FACTORS(mtch_efficacy)

```

### Run Teacher Focus EFA
```{r}
fit_mtch_focus <- EFA(mtch_focus, 
    n_factors = 3, # two factors
    rotation = "promax", 
    cor_method = "spearman", # b/c Likert
    method = c("PAF", "ML", "ULS"))
fit_mtch_focus
# save factor loadings as csv file
fit_mtch_focus_data <- cbind(fit_mtch_focus$rot_loadings, fit_mtch_focus$h2) %>% as.data.frame() 
```

### Run Teacher Efficacy EFA
```{r}
fit_mtch_efficacy <- EFA(mtch_efficacy, 
    n_factors = 2, # two factors
    rotation = "promax", 
    cor_method = "spearman", # b/c Likert
    method = c("PAF", "ML", "ULS"))
fit_mtch_efficacy
# save factor loadings as csv file
fit_mtch_efficacy_data <- cbind(fit_mtch_efficacy$rot_loadings, fit_mtch_efficacy$h2) %>% as.data.frame() 
```


# Confirmatory Factor Analysis
```{r}
library(lavaan)

## deficit framing
m1 <- 'deficit =~ m1family +  m1discipline + m1stuachieve + m1parent + m1homefx'
deficit_cfa <- cfa(m1, data = hsls)
summary(deficit_cfa)

# Efficacy of Pedagogy
m2 <- 'efficacy =~ m1stuachieve + m1retain + m1redirect + m1getthru'
efficacy_cfa <- cfa(m2, data = hsls)
summary(efficacy_cfa)

```

# Structural Equation Modelling
```{r}
sem_model <- '
# Factors
par_discuss =~ s1momtalkm + s1dadtalkm + s1momtalks + s1dadtalks 

# Regressions
x3tcredmat ~ par_sch_inv + p1eduexpect + par_discuss + frpl + par_ba + female + math_score 
s1dadtalkm	~~	s1dadtalks
s1momtalkm	~~	s1momtalks
s1dadtalkm	~~	s1momtalks
s1momtalkm	~~	s1dadtalks
p1eduexpect	~~	p1eduaspire
'
fit <- sem(sem_model, data = hsls)
summary(fit, fit.measures = TRUE)
modindices(fit, sort = TRUE)
```
```
