---
title: "parent_analysis_special_issue"
output: word_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## Load libraries and dataset
```{r}
library(tidyverse)
library(gtsummary)
library(jtools)
library(psych)
library(flextable)
library(ordinal)
df_subset <- haven::read_dta("data/hsls_subset.dta") # can use numeric values
df_analysis <- df_subset %>% haven::as_factor() #make it factors
```

# Reliability and Validity

## Subset Parent Questions for pa Year
```{r}
psd <- df_subset %>% dplyr::select(s1momtalkm, s1dadtalkm, s1momtalks, s1dadtalks)
phbae <- df_subset %>% dplyr::select(p1eduexpect, p1eduaspire, able_ba1)
school <- df_subset %>% dplyr::select(p1schevent, p1volunteer, p1fundraise, p1ptconfer, 
             p1ptomtg, p1schmtg)
```

## Reliability
```{r}
psych::reliability(psd)
psych::reliability(phbae)
psych::reliability(school)

```

# Unimputed

## Ordinal Regression
```{r}
# run ordinal regression
olr <- clm(
  data = df_analysis,
  ordered(highest_math) ~
    I(scale(psd)) + I(scale(phbae)) + I(scale(par_sch_inv)) + # parent factors
    first_lang +
    asian_ec + black_ec + another_ec + latinx_ec + multi_ec + iss +
    x1ses + female + # ses/demographics
    as.numeric(math_level1) + I(scale(math_score)) + # prior achievement
    urban + public) # school level

  # get table
olr %>% 
  tbl_regression(exp = TRUE) %>% 
  add_glance_source_note() %>% 
  add_significance_stars(
    hide_p = TRUE, hide_se = FALSE, hide_ci = FALSE) %>% 
  as_flex_table()
```

# Weighted Ordinal Regression

## Weight Model
```{r}
library(survey)

df_brr <- svrepdesign(
  weights = ~w3hstrans, 
  repweights = "w3hstrans[001-200]+",
  type = "BRR", 
  data = df_analysis,
  combined.weights = TRUE
)

```
## Ordinal Regression
```{r}

# run ordinal regression
svy_olr <- svyolr(design = df_brr,
 ordered(highest_math) ~
    I(scale(psd)) + I(scale(phbae)) + I(scale(par_sch_inv)) + # parent factors
   first_lang +
    asian_ec + black_ec + another_ec + latinx_ec + multi_ec + iss +
    x1ses + female + # ses/demographics
    as.numeric(math_level1) + I(scale(math_score)) + # prior achievement
    urban + public)

# get table
svy_olr %>% 
  tbl_regression(
    exp = TRUE) %>% 
  add_global_p() %>% 
  add_significance_stars(hide_p = TRUE, hide_se = FALSE, hide_ci = FALSE) %>% 
  as_flex_table()


```


# Imputed Data
```{r}
library(mitools)
library(mice)
load("data/df_imp.rdata")
```

## Unweighted
### Prep
```{r}

# standardize scales
df_imp$data$par_sch_inv_z <- scale(df_imp$data$par_sch_inv)
df_imp$data$phae_z <- scale(df_imp$data$phbae)
df_imp$data$math_score_z <- scale(df_imp$data$math_score)
df_imp$data$psd_z <- scale(df_imp$data$psd)
df_imp$data$native_english <- ifelse(df_imp$data$first_lang == 1, 1, 0)
df_imp$data$ell <- ifelse(df_imp$data$p1everell == 1, 1, 0)

# make highest math ordered
df_imp$data$highest_math_ord <- ordered(df_imp$data$highest_math)

# make math level numeric
df_imp$data$math_level1_num <- as.numeric(df_imp$data$math_level1)


# Effect Code Parent Race
df_imp$data$asian_par_ec <- ifelse(df_imp$data$par_race == "Asian", 1,
                        ifelse(df_imp$data$par_race == "White", -1, 0))

df_imp$data$black_par_ec <- ifelse(df_imp$data$par_race == "Black", 1,
                        ifelse(df_imp$data$par_race == "White", -1, 0))

df_imp$data$latinx_par_ec <- ifelse(df_imp$data$par_race == "Latinx", 1,
                         ifelse(df_imp$data$par_race == "White", -1, 0))

df_imp$data$multi_par_ec <- ifelse(df_imp$data$par_race == "Multiple", 1,
                              ifelse(df_imp$data$par_race == "White", -1, 0))

df_imp$data$another_par_ec <- ifelse(df_imp$data$par_race == "Indigenous", 1,
                          ifelse(df_imp$data$par_race == "White", -1, 0))


```

### Ordinal Regression
```{r}
library(ordinal)
start_time <- Sys.time()
# run ordinal regression
olr_imp <- with(
  df_imp, 
  clm(
    highest_math_ord ~
    phae_z + psd_z + par_sch_inv_z + # parent factors
    first_lang + # language
    asian_ec + black_ec + another_ec + latinx_ec + multi_ec + iss +
    x1ses + female + # ses/demographics
    math_level1_num + math_score_z + # prior achievement
    urban + public)) 

olr_imp_tbl <- summary(pool(olr_imp))

olr_imp_tbl <- olr_imp_tbl %>% mutate(
  Model = "unweighted",
  Variable = term,
  or = exp(estimate), # exponentiate estimate for ORs
  ll = exp((estimate - 1.96*std.error)), # exponentiate ll
  ul = exp((estimate + 1.96*std.error))) # exponentiate ul

write_csv(olr_imp_tbl, "tables/unweighted.csv")

olr_imp_tbl_apa <- olr_imp_tbl %>% mutate(
  LL = round(ll, 2),
  UL = round(ul, 2),
  SE = round(std.error, 2),
  stars = case_when(
      p.value < 0.001 ~ "***",
      p.value < 0.01  ~ "**",
      p.value < 0.05  ~ "*",
      TRUE ~ ""),
  or_round = round(or, 2),
  OR = paste0(formatC(or_round, format = "f", digits = 2), stars)) %>% 
  dplyr::select(Model, Variable, OR, SE, LL, UL) %>% 
  flextable() 

save_as_docx(olr_imp_tbl_apa, 
             path = "tables/Unweighted.docx")
# get table
olr_imp_apa <- olr_imp %>% tbl_regression(exp = TRUE)   %>% 
  add_glance_source_note() %>% 
  add_significance_stars(hide_p = TRUE, hide_se = FALSE, hide_ci = FALSE) 

olr_imp_apa %>% as_flex_table() %>% 
  save_as_docx(path = "tables/UNweighted Imputed Ordinal Regression.docx")

end_time <- Sys.time()
end_time - start_time

save(olr_imp, file = "data/olr_imp.rdata")
```

## Weighted
### BRR Weight Data Imputed
```{r}
# Creates a list of completed dataset for survey weights
imp_list <- imputationList(
  lapply(1:df_imp$m, function(i) complete(df_imp, i))
)

# creates BRR survey design
df_brr_imp <- svrepdesign(
  weights = ~w3hstrans, 
  repweights = "w3hstrans[001-200]+",
  type = "BRR", 
  data = imp_list,
  combined.weights = TRUE
)

```

### Ordinal Regression Model
```{r}

start_time <- Sys.time()

# run ordinal regression
olr_imp_svy <- with(
  df_brr_imp, 
  svyolr(
    highest_math_ord ~
    phae_z + psd_z + par_sch_inv_z + # parent factors
    first_lang + # language
    asian_ec + black_ec + another_ec + latinx_ec + multi_ec + iss +
    x1ses + female + # ses/demographics
    math_level1_num + math_score_z + # prior achievement
    urban + public)) 

# save model as rdata file
save(olr_imp_svy, file =  "data/olr_imp_svy.rdata")

# get time for analysis, took around 50 minutes
end_time <- Sys.time()
end_time - start_time
```

### Ordinal Regression Tables
```{r}
load("data/olr_imp_svy.rdata")
# get table
olr_imp_svy_tbl <- summary(pool(olr_imp_svy))

olr_imp_svy_tbl <- olr_imp_svy_tbl %>% mutate(
  Model = "weighted",
  Variable = term,
  or = exp(estimate), # exponentiate estimate for ORs
  ll = exp((estimate - 1.96*std.error)), # exponentiate ll
  ul = exp((estimate + 1.96*std.error))) # exponentiate ul

write_csv(olr_imp_svy_tbl, "tables/weighted.csv")

olr_imp_svy_tbl_apa <- olr_imp_svy_tbl %>% mutate(
  LL = round(ll, 2),
  UL = round(ul, 2),
  SE = round(std.error, 2),
  stars = case_when(
      p.value < 0.001 ~ "***",
      p.value < 0.01  ~ "**",
      p.value < 0.05  ~ "*",
      TRUE ~ ""),
  or_round = round(or, 2),
  OR = paste0(formatC(or_round, format = "f", digits = 2), stars)) %>% 
  dplyr::select(Model, Variable, OR, SE, LL, UL) %>% 
  flextable() 

save_as_docx(olr_imp_svy_tbl_apa, 
             path = "tables/Weighted.docx")

```

# Forest Plots
```{r}
# remember to save in figures folder!
```

